// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzDcRrHq0INAVaB3GM2s23fhJ7TDGac80',
    appId: '1:874205589621:web:0d598c36f55f0e8590483c',
    messagingSenderId: '874205589621',
    projectId: 'ecommerceapp-ddeb7',
    authDomain: 'ecommerceapp-ddeb7.firebaseapp.com',
    storageBucket: 'ecommerceapp-ddeb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNho2zuTX6PGC3RmbC0PVfe7WM2Bs_iE',
    appId: '1:874205589621:android:f137a80fad057cef90483c',
    messagingSenderId: '874205589621',
    projectId: 'ecommerceapp-ddeb7',
    storageBucket: 'ecommerceapp-ddeb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHD-gXv3n3Je7VQ-AezJPFRpI0DHiH0lE',
    appId: '1:874205589621:ios:ef4237040b70541d90483c',
    messagingSenderId: '874205589621',
    projectId: 'ecommerceapp-ddeb7',
    storageBucket: 'ecommerceapp-ddeb7.firebasestorage.app',
    androidClientId: '874205589621-ccplcballg2qubtaamc55o9thr9oe7r0.apps.googleusercontent.com',
    iosClientId: '874205589621-lnbgkelni4vaocl2052l0liddkrh47s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHD-gXv3n3Je7VQ-AezJPFRpI0DHiH0lE',
    appId: '1:874205589621:ios:ef4237040b70541d90483c',
    messagingSenderId: '874205589621',
    projectId: 'ecommerceapp-ddeb7',
    storageBucket: 'ecommerceapp-ddeb7.firebasestorage.app',
    androidClientId: '874205589621-ccplcballg2qubtaamc55o9thr9oe7r0.apps.googleusercontent.com',
    iosClientId: '874205589621-lnbgkelni4vaocl2052l0liddkrh47s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzDcRrHq0INAVaB3GM2s23fhJ7TDGac80',
    appId: '1:874205589621:web:96d934df51a7846290483c',
    messagingSenderId: '874205589621',
    projectId: 'ecommerceapp-ddeb7',
    authDomain: 'ecommerceapp-ddeb7.firebaseapp.com',
    storageBucket: 'ecommerceapp-ddeb7.firebasestorage.app',
  );

}